### GET clear counters
GET http://localhost:8080/clear

### GET httpbin
GET https://httpbin.org/delay/5

### GET blocked request
GET http://localhost:8080/block/5

### GET partial reactive request
GET http://localhost:8080/partialReactiveBlocks/1000/threads/5