name: Build and Push to GHCR

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Kódbázis klónozása
        uses: actions/checkout@v4

      - name: Java 21 beállítása
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Függőségek telepítése és build
        run: ./mvnw clean package -DskipTests

      - name: Docker bejelentkezés GitHub Container Registry-hez
        run: echo "${{ secrets.PERSONAL_GITHUB_TOKEN }}" | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin

      - name: Docker image build (Alpine)
        run: |
          IMAGE_NAME=ghcr.io/${{ github.actor }}/virtualthreaddemo
          docker build -t $IMAGE_NAME:latest -f Dockerfile.alpine .
          docker tag $IMAGE_NAME:latest $IMAGE_NAME:${{ github.sha }}

      - name: Trivy telepítése
        run: |
          sudo apt-get update
          sudo apt-get install -y wget apt-transport-https gnupg lsb-release
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
          echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install -y trivy

      - name: Docker image biztonsági ellenőrzése (Trivy)
        run: |
          IMAGE_NAME=ghcr.io/${{ github.actor }}/virtualthreaddemo
          trivy image --exit-code 1 --severity HIGH,CRITICAL $IMAGE_NAME:latest

      - name: Docker image feltöltése GHCR-re
        run: |
          IMAGE_NAME=ghcr.io/${{ github.actor }}/virtualthreaddemo
          docker push $IMAGE_NAME:latest
          docker push $IMAGE_NAME:${{ github.sha }}

      - name: Docker image mentése artifaktként
        uses: actions/upload-artifact@v4
        with:
          name: virtualthreaddemo-image
          path: |
            $(docker save ghcr.io/${{ github.actor }}/virtualthreaddemo:latest -o virtualthreaddemo_latest.tar)
            virtualthreaddemo_latest.tar